config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :gig

  get 'pages/updatebulk', to: "gig#updatebulk", as: 'updatebulk'
  get 'pages/uploadfiles', to: "pages#uploadfiles", as: "uploadfiles"
  get 'tutoriel', to: "pages#tutoriel", as: "tutoriel"

  post 'upload', to: "pages#upload", as: :upload

  root to: 'pages#main', as: 'main'
  get 'retrieve', to: 'gig#retrieve_new_monthly_datas', as: 'retrieve'

  get 'history', to: 'gig#retrieve_history_data_from_2012', as: 'history'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gig.rb
class Gig < ApplicationRecord
    #devise :database_authenticatable, :registerable,
     #    :recoverable, :rememberable, :trackable, :validatable

  scope :year, -> (year) { where year: year }
  scope :month, -> (month) { where month: month }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/gig_controller.rb
#require_relative '../services/parse_xls_edt_service'

class GigController < ApplicationController
  before_action :authenticate_user!

  def index

    @gigs = Gig.where(nil) # creates an anonymous scope
    @gigs = @gigs.year(params[:year]) if params[:year].present?
    @gigs = @gigs.month(params[:month]) if params[:month].present?

    @gigssorted = @gigs.sort_by do |item|
      item.id
    end

    @month = params[:month] if params[:month].present?
    @year = params[:year] if params[:year].present?
    @years_array = Gig.select(:year).distinct.order(year: :desc)
    @sommeinterne = Gig.where(year:params[:year], month: params[:month]).sum(:quantity_interne)
    @sommeedt = Gig.where(year:params[:year], month: params[:month]).sum(:quantity_edt)

    @stats_overview = Gig.find_by_sql("SELECT
    title,
    SUM(quantity_interne) AS total_estimated_quantity,
    SUM(quantity_edt) AS total_billed_quantity,
    (SUM(quantity_interne) - SUM(quantity_edt)) AS delta
    FROM gigs WHERE year = @year  GROUP BY title ORDER BY title")

   @stats_year = Gig.find_by_sql("SELECT

    SUM(quantity_interne) AS total_estimated_quantity,
    SUM(quantity_edt) AS total_billed_quantity,
    (SUM(quantity_interne) - SUM(quantity_edt)) AS delta
    FROM gigs WHERE year = @year")


   @stats_evolution = Gig.find_by_sql("SELECT
    year,
    SUM(quantity_interne) AS total_estimated_quantity,
    SUM(quantity_edt) AS total_billed_quantity,
    (SUM(quantity_interne) - SUM(quantity_edt)) AS delta
    FROM gigs GROUP BY year ORDER BY year DESC")


=begin      @stats_per_month = Gig.select("
      title,
      month,
      SUM(quantity_interne) AS total_estimated_quantity,
      SUM(quantity_edt) AS total_billed_quantity,
      (SUM(quantity_interne) - SUM(quantity_edt)) AS delta"
    ).group("month, title").order(:month, :title).group_by(&:month)
=end

  end

  def show
  end

  def retrieve_new_monthly_datas

    month = params[:month]
    year = params[:year]


    #on met à jour le model gig avec la nouvelle facture EDT pour un mois donné
    Parse_xls_Edt_Service.parse_and_insert(year.to_i,month.to_i)

   # on va chercher les datas sur le tableau de edt
    # itemsedt = ParsexlsEdtService.parse_and_insert

    # itemsedt.each do |item|
    # @gig = Gig.new(title: item[:title], price: 0, source: 0, year: year, month: month, quantity_interne: 0, quantity_edt: item[:value])
    #  @gig.save!
    # end

    #on va chercher les datas sur les tableaux cecurity pour un mois donné et on update le model gig
    arrayitems = MatchFilesCecurityService.match(year.to_i, month.to_i)

    #arrayitems.each do |item|
     # @selectedgig = Gig.where("title LIKE :query AND year = :year AND month = :month", query: "%#{item[:title]}%", year: year, month: month)
      #@selectedgig.update(quantity_interne: item[:value])
    #end




    #QueryOracleApofService.query(year.to_i, month.to_i)


    #On met à jour le CSV de données globale
    DownloadModelGigIntoCsv.fill_in_csv

    # on redirige vers cette même page
    redirect_to gig_index_path
  end


  def create
  end



  def edit
  end

  def self.update(year, month)
   #arrayitems = MatchFilesCecurityService.match(year, month)
    #puts 'waaaaooo'
    #puts arrayitems
    #puts 'waaaaooo2'

    #arrayitems.each do |item|
     #   @selectedgig = Gig.where("title LIKE :query AND year = :year AND month = :month", query: "%#{item[:title]}%", year: year, month: month)
     #   @selectedgig.update(quantity_interne: item[:value])
    #end


    #itemsedt = ParsexlsEdtService.parse
    #itemsedt.each do |item|
     #   @selectedg = Gig.where("title LIKE :query AND year = :year AND month = :month", query: "%#{item[:title]}%", year: year, month: month)
     #   @selectedg.update(quantity_edt: item[:value])
    #end
  end

  def retrieve_history_data_from_2012


    if Gig.last.nil?

      results = ParsexlsHistoryService.parse

    end
  redirect_to gig_index_path
  end

  def self.fill_in_csv_with_displayed_gigs
    DownloadModelGigIntoCsv.fill_in_csv
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :main

  def uploadfiles
    @month = params[:month]
    @year = params[:year]

  end

  def tutoriel
  end

  def traitement
  end

  def upload

    filececurity = params[:filececurity]
    fileedt = params[:fileedt]
    @month = params[:month]
    @year = params[:year]

    Gig.where(month: @month, year: @year).destroy_all


  filececurity.each do |item|
    File.open(Rails.root.join('public', 'uploads' ,'cecurity', item.original_filename), 'wb') do |file|
      file.write(item.read)
    end
  end

    File.open(Rails.root.join('public', 'uploads' , 'edt', fileedt.original_filename), 'wb') do |file|
     file.write(fileedt.read)
    end

    #render plain: "Upload effectué"
    redirect_to uploadfiles_path(month:@month, year:@year)
  end

  def main
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gig_helper.rb
module GigHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gig/index.html.erb
<div class="container">
  <h2> Quantité estimée VS quantité facturée </h2>

<%= link_to "Télécharger l'historique des données", "/downloads/alldatas.csv", data: { no_turbolink: true }, class:'btn btn-primary' %>

<div class="menuyear">
  <ul class="flexbox" id="yearlist">
    <% @years_array.each do |item| %>
      <% if item.year > 2000 %>
        <li class="navbar-wagon-item navbar-wagon-link"><%= item.year %></li>
      <% end %>
    <% end %>
  </ul>
</div>


  <div id="range" class="hidden">
    <div id="yearlink"><a href="">    Cumul Annuel</a></div>
    <hr>
    <div id="monthlist">
      <div class="flexdate">
        <div class="bg-light">
          <ul>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Janvier</a></li>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Février</a></li>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Mars</a></li>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Avril</a></li>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Mai</a></li>
            <li class="navbar-wagon-item navbar-wagon-link"><a href="">Juin</a></li>
          </ul>
      </div>
      <div class="bg-light">
        <ul>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Juillet</a></li>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Aout</a></li>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Septembre</a></li>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Octobre</a></li>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Novembre</a></li>
          <li class="navbar-wagon-item navbar-wagon-link"><a href="">Décembre</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% if !@month.nil? %>

  <h4> Mois : <%= @month %> Année : <%= @year %></h4>
  <div>
    <div class="dashboard">
      <ul class="flexbox header">
        <li class="flexitem1">Titre</li>
        <li class="flexitem2">Année</li>
        <li class="flexitem2">Mois</li>
        <li class="flexitem2">Quantité estimée</li>
        <li class="flexitem2">Quantité facturée EDT</li>
        <li class="flexitem2">Delta</li>
      </ul>
      <hr>
      <ul class="flexbox header">
        <li class="flexitem1">Total mensuel</li>
        <li class="flexitem2"></li>
        <li class="flexitem2"></li>
        <li class="flexitem2"><%= @sommeinterne %></li>
        <li class="flexitem2"><%= @sommeedt  %></li>

      <% if (@sommeedt - @sommeinterne) > 1 %>
        <li class="flexitem2 redcolor"><%= @sommeedt - @sommeinterne %></li>
      <% else %>
      <li class="flexitem2"><%= @sommeedt - @sommeinterne %></li>
      <% end %>
      </ul>
      <hr>
      <ul>


      <% @gigssorted.each do |item| %>
        <li>
          <ul class="flexbox">
            <li class="flexitem1"><%= item.title %></li>
            <li class="flexitem2"><%= item.year %></li>
            <li class="flexitem2"><%= item.month %></li>
            <li class="flexitem2"><%= item.quantity_interne %></li>
            <li class="flexitem2"><%= item.quantity_edt %></li>
            <% if (item.quantity_edt - item.quantity_interne) > 1 %>
            <li class="flexitem2 redcolor"><%= item.quantity_edt - item.quantity_interne %></li>
            <% else %>
            <li class="flexitem2"><%= item.quantity_edt - item.quantity_interne %></li>
            <% end %>
          </li>
          </ul>
        </li>
      <% end %>
      </ul>
    </div>
  </div>

  <% end %>



<% if @month.nil? %>

    <div class="dashboard-yearly">
      <ul class="flexbox header">
        <li class="flexitem1">Titre</li>
        <li class="flexitem2">Année</li>
        <li class="flexitem2">Mois</li>
        <li class="flexitem2">Quantité estimée</li>
        <li class="flexitem2">Quantité facturée EDT</li>
        <li class="flexitem2">Delta</li>
      </ul>
      <hr>
      <ul class="flexbox header">
        <li class="flexitem1">Cumul annuel</li>
        <li class="flexitem2"></li>
        <li class="flexitem2"></li>
      <% @stats_year.each do |stats| %>
        <li class="flexitem2"><%= stats.total_estimated_quantity %></li>
        <li class="flexitem2"><%= stats.total_billed_quantity %></li>
      <% if stats.delta > 1 %>
        <li class="flexitem2 redcolor"><%= stats.delta %></li>
      <% else %>
        <li class="flexitem2"><%= stats.delta %></li>
      <% end %>
      </ul>

      <hr>

      <ul>
       <% @stats_overview.each do |stats| %>
        <li>
          <ul class="flexbox">
            <li class="flexitem1"><%= stats.title %></li>
            <li class="flexitem2"></li>
            <li class="flexitem2"></li>
            <li class="flexitem2"><%= stats.total_estimated_quantity %></li>
            <li class="flexitem2"><%= stats.total_billed_quantity %></li>
            <% if (stats.total_billed_quantity - stats.total_estimated_quantity) > 1 %>
            <li class="flexitem2 redcolor"><%= stats.total_billed_quantity - stats.total_estimated_quantity %></li>
            <% else %>
            <li class="flexitem2"><%= stats.total_billed_quantity - stats.total_estimated_quantity %></li>
            <% end %>
          </ul>
        </li>
        <% end %>
      </ul>

    <% end %>

</div>
<% end %>


<h2> Evolution annuelle des quantités facturées </h2>
<div class="dashboard">
  <ul class="row header">
    <li class="col col-lg-3">Année</li>
    <li class="col col-lg-3">Quantité estimée</li>
    <li class="col col-lg-3">Quantité facturée EDT</li>
    <li class="col col-lg-3">Delta</li>
  </ul>

  <% @stats_evolution.each do |item| %>
   <ul class="row">
    <li class="col col-lg-3"><%= item.year %></li>
    <li class="col col-lg-3"><%= item.total_estimated_quantity %></li>
    <li class="col col-lg-3"><%= item.total_billed_quantity %></li>
    <li class="col col-lg-3"><%= item.delta %></li>
  </ul>
  <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Printus</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>


    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>








  </head>
  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>








    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/main.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1526633731461-c7903581c0bd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1c06a3764f00be9f50bc270c59c98b0d&auto=format&fit=crop&w=1350&q=80');">
  <div class="banner-content">
    <h1>PRINTus</h1>
    <p>Automated invoice checking </p>


    <% if user_signed_in? %>
    <%= link_to 'Dashboard', gig_index_path, class:'btn btn-success btn-lg'%>
    <% else %>
    <%= link_to 'Log In',new_user_session_path, class:'btn btn-primary btn-lg'%>
    <% end %>

  </div>
</div>

app/views/pages/tutoriel.html.erb
<div class="container">
<h1>Tutoriel</h1>
<br>
<H4>Modification des constantes</H4>
<p>Dans le cas ou les formats des fichiers XLS, XLS ou le paramétrage d'accès à la base APOF changeraient, il existe un fichier de config modifiable</p>
<p> Aller dans l'arborescence de l'application et ouvrir le fichier
config/initializers/my_constant.rb"
</p>

<h4>Mettre à jour les données d'un mois M-1</h4>
<p>Afin de mettre à jours les données EDT, CECURITY et APOF procéder ainsi</p>

<ul>
<li> - Cliquer sur le lien "Mettre à jour" accessible depuis la barre de navigation.</li>
<li> - Selectionner le mois et l'année à mettre à jour.</li>
<li> - Uploader le dernier fichier XLS semestriel envoyé par EDT</li>
<li> - Uploader tous les fichiers CSV envoyés par CECURITY pour mettre à jour ce mois M</li>
<li> - Cliquez sur "Envoyer"</li>
<li> - Cliquer sur "insérer les données", étape indispensable pour enregsitrer les données en base</li>
</ul>

<p> Si par erreur vous n'avez pas uploadé tous les fichiers pour le mois en question, réeitérer l'opération. L'application écrase toutes les entrées enregistrées précédement pour ce mois M<br>

<p> Lors de ce processus la base de données APOF est également appelée afin de mettre à jour les six premiers items de la colonne "quantité estimée" pour les items ci-dessous:<br>


#1 - Archives uniquement<br>
#2 - Original PFP vers Annonceur avec archivage<br>
#2 - Original PFP vers Annonce<br>
#2 - Original PFP vers Annonce
#3 - Original PDF vers Editique avec archivage<br>
#2 - Original PFP vers Annonce
#4 - Copie PFP vers Agence sans archivage<br>
#2 - Original PFP vers Annonce
#5 - Copie PDF vers Editique sans archivage<br>
#2 - Original PFP vers Annonce
#6 - Copie PDF vers Agence sans archivage<br>
#2 - Original PFP vers Annonce
</p>

<h4>Comparer les quantités estimées et celles facturées par le prestataire EDT</h4>
<p> Après avoir uploadé les données EDT, CECURITY et APOF via l'étape ci-dessous, vous pourrez vérifier si les volumes facturés par EDT sont correctes.</p>
<p> Cliquez sur lien "Tableau"</p>
<p> Selectionnez l'année et le mois que vous souhaitez vérifier</p>
<p> S'il existe une différence entre les quantités estimées par M6 et les quantités facturées apr EDT, vous pourrez l'observer dans la colonne delta.</p>
<p> Lorsque la celulle de la colonne "delta" s'affiche en rouge, cela signife qu'EDT a facturé plus que ce qu'il n'aurait dû.</p>

<p> Notez que vous trouverez également sur cette même page l'évolution annuelle des quantités facturées. </p>

<h4>Récupérer toutes les données au format CSV</h4>
<p> Cliquez sur le lien "tableau", accessible depuis la barre de navigation puis Cliquez sur "Télécharger l'historique des données".</p>
<p> Vous disposerez alors de toutes les données saisies depuis 2012, y compris celles mises à jour depuis l'application PrintUs.</p>

</div>

app/views/pages/uploadfiles.html.erb
<div class="container">

  <% if @month == nil || @year == nil %>

    <div class="row">
      <div class="col-lg-6">


      <%= form_tag('/upload', multipart: true, class:'formuploadfiles') do %>


      <div class="form-group">
        <label for="month"> Mois à mettre à jour</label>

        <%= select_tag 'month', options_for_select({ "January" => 1, "February" => 1, "March" => 3, "April" => 4, "May" => 5, "June" => 6, "july" => 7, "August" => 8, "September" => 9, "October" => 10, "November" => 11,"December" => 12 }) %>

    <!--     <%= select_tag 'month', options_for_select([ "January", "February", "march", "april", "may", "june", "july","august", "september", "October", "November", "December" ]) %> -->

         <label for="year"> Année à mettre à jour</label>
        <%= select_tag 'year', options_for_select([ Date.today.strftime("%Y"), Date.today.strftime("%Y").to_i - 1, Date.today.strftime("%Y").to_i - 2, Date.today.strftime("%Y").to_i- 3, Date.today.strftime("%Y").to_i - 4, Date.today.strftime("%Y").to_i - 5, Date.today.strftime("%Y").to_i - 6])%>
      </div>

      <div class="form-group">
        <label for="fileedt">Récap mensuel EDT</label>
        <%= file_field_tag 'fileedt', class: 'form-control' %>
      </div>

<!--
      <div class="form-group">
        <label for="filececurity">Fichiers Cecurity</label>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
        <%= file_field_tag 'filececurity', class: 'form-control' %>
      </div>
      -->


      <label for="filececurity[]">Fichiers Cecurity</label>
      <%= file_field(:post, :image, :multiple => true, :name => 'filececurity[]') %>



      <%= submit_tag 'Envoyer', class: 'btn btn-primary' %>
      <% end %>

      </div>
    </div>

<% else %>

<div class="span5" style="margin-top:20px;">
  <p>Les données ont été traitées avec succès pour <%= @month %> / <%= @year %></p>
  <%= link_to "Insérer les données", retrieve_path(year:@year,month:@month), class: 'btn btn btn-primary' %>
</div>
<% end %>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
   <!--
  <%= link_to main_path, class: "navbar-wagon-brand" do %>

    <%= image_tag "logo.png", height: 50 %>
    <% end %>
     -->

    <h1><%= link_to "PRINTus", gig_index_path %></h1>
    <i class="fas fa-file-invoice"></i>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Tableau", gig_index_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mettre à jour", "/pages/uploadfiles.html", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Tutoriel", tutoriel_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
  -->

    <% else %>
      <!-- Login link (when logged out)
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>   -->

  </div>


  <!-- Dropdown list appearing on mobile only
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
 -->
</div>